# fly.toml app configuration file generated for xflystudio-backend on 2023-05-18T16:34:23+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "xflystudio-backend"
primary_region = "nrt"

[build]
  builder = "heroku/buildpacks:20"
  
[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
